### ISSUE TITLE
Add props to sidebar

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/victory-docs#133]
> the only thing that would be really nice to add would be a little sidebar list of the props a la lodash https://lodash.com/docs/4.16.0
> or maybe add that nested to the existing sidebar

So, I think this means the sidebar would look like:
 
```markdown
**Documentation**
 Core
   VictoryAnimation
     children
     duration
     easing
     delay
     onEnd
     data
   VictoryLabel
     angle
     capHeight
     datum
     data
     events
     text
     children
     lineHeight
     style
     textAnchor
     verticalAnchor
     transform
     x
     y
     dx
     dy

[etc]
```

**Comment by boygirl** [comment]
@paulathevalley yes, but the nested part should only show when you're on that page

**Comment by rawrmonstar** [comment]
@paulathevalley @boygirl Will the props in the sidebar be links to the prop in the table of props on each component page? Or something else?

**Comment by rawrmonstar** [comment]
@paulathevalley @boygirl  Which props should appear under the `VictoryTooltip` link? The page contains documentation for both `VictoryTooltip` and `VictoryVoronoiTooltip`. Ecology generates a prop table for `VictoryVornoiTooltip` at the bottom of the page but it'd be pretty confusing for the `VictoryVoronoiTooltip` props to appear under the `VictoryTooltip` link since `VictoryTooltip` doesn't accept the same props as `VictoryVoronoiTooltip`.
