### ISSUE TITLE
Split up developer documentation into simple and advanced

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-docs#14]
_From @coopy on March 18, 2016 23:48_
- Simple doesn't mention builder
- Advanced introduces builder

_Copied from original issue: FormidableLabs/victory#230_

**Comment by paulathevalley** [comment]
Hi team! What’s the status on this issue? Is it still relevant? If yes, who will be on point for writing?

**Comment by coopy** [comment]
I’ll let Ken determine if this is still relevant.

On October 24, 2016 at 12:30:17 PM, Paula Lavalle (notifications@github.com)
wrote:

Hi team! What’s the status on this issue? Is it still relevant? If yes, who
will be on point for writing?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FormidableLabs/victory-docs/issues/14#issuecomment-255840960>,
or mute the thread
