### ISSUE TITLE
Guide for building from src not lib

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-docs#23]
_From @knowbody on January 3, 2016 17:52_

A more advanced guide for building / babelifying from `src/` not `lib/` for tighter, fully source-mapped builds.

Based on the #144 and chat with @ryan-roemer

_Copied from original issue: FormidableLabs/victory#146_

**Comment by paulathevalley** [comment]
Hi team! What’s the status on this issue? Is it still relevant? If yes, who will be on point for writing it?

**Comment by coopy** [comment]
Not sure. @ryan-roemer, what do you think?

On October 24, 2016 at 12:31:51 PM, Paula Lavalle (notifications@github.com)
wrote:

Hi team! What’s the status on this issue? Is it still relevant? If yes, who
will be on point for writing it?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/FormidableLabs/victory-docs/issues/23#issuecomment-255841450>,
or mute the thread

**Comment by ryan-roemer** [comment]
Let's roll this into https://github.com/FormidableLabs/victory/issues/256
