### ISSUE TITLE
Add Common Props page to docs

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-docs#303]
The common props page will have a list of props corresponding to https://github.com/FormidableLabs/victory-chart/blob/master/src/helpers/common-props.js

Common props introduction section should explain that:

Not every component uses all of these props. These are all common to things like `VictoryBar`, `VictoryScatter` but other components like `VictoryStack` use only some of them.

The props explanations given here are general, and that component docs pages are the source of truth for a component's props, and any caveats will be listed there.

props that vary a bit from component to component (like the namespaces in `style`) will be specifically called out

**Comment by ianwsperber** [comment]
The common props are supposed to be prioritized in the sidebar search over the per component props. Since the sidebar search effectively acts as a filter, the simplest implementation will be to include the common props as the first page under the `Documentation` heading, perhaps with its own subheading. This way we can avoid sidebar items changing order while you search.
