### ISSUE TITLE
VictoryContainer example

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-docs#384]
People seem to be using it in strange ways. Docs must not be thorough enough.

**Comment by AuthorOfTheSurf** [comment]
I tried using it to wrap `<VictoryChart>` to get access to the container dimensions through a ref and it made my chart disappear. I must be using this totally wrong, so even a single example on the doc site would help me a lot. I haven't worked with `<svg>` that much so that is certainly one area that I am probably misunderstanding.

```js
<VictoryContainer
    containerRef={ref => (this.containerRef = ref)}
>
    <VictoryChart
        theme={theme}
        domainPadding={50}
    >
        <VictoryAxis
            tickValues={R.map(R.prop(xKey), data)}
            tickFormat={xTickFormat}
            style={xAxisStyles}
        />
        <VictoryAxis
            dependentAxis
            tickFormat={yTickFormat}
        />
        <VictoryBar
            data={data}
            x={xKey}
            y={yKey}
        />
    </VictoryChart>
</VictoryContainer>
```

Also took a look at the tests, but none of the cases involve using `VictoryContainer` to wrap child components: https://github.com/FormidableLabs/victory-core/blob/master/test/client/spec/victory-container/victory-container.spec.js

What I am trying to do is provide a layer over Victory charts, where the developer can set a couple of props on the container, then the chart will render optimally. I am going for two modes. One will be using up every bit of space available (`"FIT"`), the second will be overflowing to the side in cases where we are graphing 30+ items on a bar chart (`"OVERFLOW"`). Logically, I thought that VictoryContainer would give me a better API into this stuff than a simple `<div>` that wraps `<VictoryChart>` so that's how I was trying to use it.

**Comment by boygirl** [comment]
@AuthorOfTheSurf The issue is that `VictoryContainer` should not _wrap_ `VictoryChart`. Examples have been added to the docs including in the new FAQ section. Check it out: https://formidable.com/open-source/victory/docs/faq#how-can-i-use-containers-in-victory-
